"""Phase 0 coverage audit of the Oracc aemw/amarna corpus.

Reads data/raw/aemw/amarna/ (extracted from aemw-amarna.zip) and writes
coverage_report.md at the repo root. Rerunnable any time the corpus is
re-downloaded; every number in the report comes from this script.
"""

import collections
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "data" / "raw" / "aemw" / "amarna"
REPORT = ROOT / "coverage_report.md"

# EA numbers per Knudtzon + later additions: EA 1-382 (with known gaps in
# scholarship itself, e.g. EA 380-382 are Rainey's additions).
EA_MAX = 382


def parse_ea(designation: str):
    m = re.match(r"EA ([0-9]+)([a-z]?)", designation)
    return (int(m.group(1)), m.group(2)) if m else None


def walk_cdl(node, words):
    """Collect word ('l') nodes from an Oracc CDL tree."""
    if isinstance(node, dict):
        if node.get("node") == "l":
            words.append(node)
        for child in node.get("cdl", []):
            walk_cdl(child, words)
    elif isinstance(node, list):
        for child in node:
            walk_cdl(child, words)


def lemmatization_stats(pfile: Path):
    """Return (n_words, n_lemmatized) for one corpusjson file."""
    data = json.loads(pfile.read_text())
    words = []
    walk_cdl(data.get("cdl", []), words)
    n_lem = sum(1 for w in words if "cf" in w.get("f", {}) or "sense" in w.get("f", {}))
    return len(words), n_lem


def main():
    cat = json.loads((CORPUS / "catalogue.json").read_text())
    members = cat["members"]
    pfiles = {p.stem: p for p in (CORPUS / "corpusjson").glob("P*.json")}

    # --- field coverage over catalogue members ---
    field_counts = collections.Counter(k for v in members.values() for k in v)

    # --- EA designation coverage ---
    ea_present = {}
    non_ea = []
    for pid, v in members.items():
        ea = parse_ea(v.get("designation", ""))
        if ea:
            ea_present.setdefault(ea[0], []).append((pid, v))
        else:
            non_ea.append((pid, v.get("designation", "?")))
    ea_missing = [n for n in range(1, EA_MAX + 1) if n not in ea_present]

    def ranges(nums):
        out, start, prev = [], None, None
        for n in nums:
            if start is None:
                start = prev = n
            elif n == prev + 1:
                prev = n
            else:
                out.append((start, prev))
                start = prev = n
        if start is not None:
            out.append((start, prev))
        return ", ".join(f"{a}" if a == b else f"{a}-{b}" for a, b in out)

    # --- members with/without corpus text ---
    with_text = [pid for pid in members if pid in pfiles]
    without_text = [pid for pid in members if pid not in pfiles]
    orphan_files = [pid for pid in pfiles if pid not in members]

    # --- genre / subgenre ---
    subgenres = collections.Counter(
        f"{v.get('genre', '?')} / {v.get('subgenre', '?')}" for v in members.values()
    )
    proveniences = collections.Counter(v.get("provenience", "?") for v in members.values())

    # --- sender / recipient structured-field audit ---
    def norm(v, key):
        val = (v.get(key) or "").strip()
        return val if val and val != "[missing]" else None

    senders = collections.Counter()
    recipients = collections.Counter()
    n_sender, n_recipient = 0, 0
    for v in members.values():
        s, r = norm(v, "ancient_author"), norm(v, "recipient")
        if s:
            n_sender += 1
            senders[s] += 1
        if r:
            n_recipient += 1
            recipients[r] += 1

    # --- lemmatization coverage over corpusjson ---
    lem_rows = []
    for pid, pf in sorted(pfiles.items()):
        n_words, n_lem = lemmatization_stats(pf)
        lem_rows.append((pid, n_words, n_lem))
    total_words = sum(r[1] for r in lem_rows)
    total_lem = sum(r[2] for r in lem_rows)
    unlemmatized_texts = [r for r in lem_rows if r[1] > 0 and r[2] / r[1] < 0.5]

    ts = cat.get("UTC-timestamp", "?")
    lines = []
    a = lines.append
    a("# Coverage Report — Oracc `aemw/amarna` (Phase 0 deliverable)")
    a("")
    a(f"Generated by `scripts/audit_coverage.py` from `aemw-amarna.zip` "
      f"(catalogue UTC-timestamp: **{ts}**).")
    a("")
    a("## Headline numbers")
    a("")
    a(f"- Catalogue members: **{len(members)}**")
    a(f"- Texts with corpusjson (transliterated+lemmatized): **{len(with_text)}**")
    a(f"- Catalogue members with no corpusjson file: **{len(without_text)}**")
    a(f"- Orphan corpusjson files not in catalogue: **{len(orphan_files)}**")
    a(f"- Word tokens across corpus: **{total_words:,}**, of which lemmatized: "
      f"**{total_lem:,}** ({100 * total_lem / total_words:.1f}%)")
    a(f"- Texts with <50% lemmatization: **{len(unlemmatized_texts)}**")
    a("")
    a("## Structured sender/recipient fields — PLAN CORRECTION")
    a("")
    a("The project plan (PLAN.md §2.1) claims the catalogue has **no** structured")
    a("sender/addressee fields and budgets Phase 1 around parsing address formulae.")
    a("**This is wrong for the raw `catalogue.json`** (the plan checked the pager")
    a("display config only):")
    a("")
    a(f"- `ancient_author` (sender) present and non-missing: **{n_sender}/{len(members)}**"
      f" ({len(senders)} distinct raw values)")
    a(f"- `recipient` present and non-missing: **{n_recipient}/{len(members)}**"
      f" ({len(recipients)} distinct raw values)")
    a("")
    a("Consequence: the Phase 1 header parser is demoted from critical-path to a")
    a("validation/backfill tool. Entity resolution across raw value variants is")
    a("still required (registry keyed on these strings + lemma IDs).")
    a("")
    a("### Top senders (raw strings, uncollapsed)")
    a("")
    for name, c in senders.most_common(15):
        a(f"- {c:3d}  {name}")
    a("")
    a("### Top recipients (raw strings, uncollapsed)")
    a("")
    for name, c in recipients.most_common(10):
        a(f"- {c:3d}  {name}")
    a("")
    a("### Great Powers letters (EA 1-44)")
    a("")
    gp = []
    for pid, v in members.items():
        ea = parse_ea(v.get("designation", ""))
        if ea and ea[0] <= 44 and not ea[1]:
            gp.append((ea[0], norm(v, "ancient_author"), norm(v, "recipient")))
    gp_both = sum(1 for _, s, r in gp if s and r)
    a(f"Not yet lemmatized (no corpusjson), but **{gp_both}/{len(gp)}** already have")
    a("both structured sender and recipient in the catalogue. The plan's Phase 1")
    a("task 'hand-code EA 1-44 sender/addressee from Moran/Rainey' therefore")
    a("reduces to (a) validating these fields and (b) hand-coding *mentions* only.")
    a("Known quirk to fix in Phase 1: EA 7 lists recipient 'Babylon' (should be a")
    a("pharaoh, per Moran).")
    a("")
    a("## EA number coverage")
    a("")
    a(f"- Distinct EA numbers in catalogue: **{len(ea_present)}** (of EA 1-{EA_MAX})")
    a(f"- Non-EA designations: **{len(non_ea)}** "
      f"({'; '.join(d for _, d in non_ea[:10])}{'...' if len(non_ea) > 10 else ''})")
    a(f"- Missing EA numbers: {ranges(ea_missing)}")
    a("")
    ea_no_text = sorted(
        n for n, entries in ea_present.items()
        if not any(pid in pfiles for pid, _ in entries)
    )
    a(f"- EA numbers in catalogue but with **no corpus text**: {ranges(ea_no_text)}")
    a("")
    a("## Genre / subgenre breakdown")
    a("")
    for g, c in subgenres.most_common():
        a(f"- {c:3d}  {g}")
    a("")
    a("## Provenience breakdown (top 20)")
    a("")
    for p, c in proveniences.most_common(20):
        a(f"- {c:3d}  {p}")
    a("")
    a("## Catalogue field coverage")
    a("")
    a("| field | members with field |")
    a("|---|---|")
    for k, c in field_counts.most_common():
        a(f"| `{k}` | {c} |")
    a("")
    a("## Texts with <50% lemmatization")
    a("")
    if unlemmatized_texts:
        for pid, n_words, n_lem in unlemmatized_texts:
            desig = members.get(pid, {}).get("designation", "?")
            a(f"- {pid} ({desig}): {n_lem}/{n_words} words lemmatized")
    else:
        a("None.")
    a("")

    REPORT.write_text("\n".join(lines))
    print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
