"""Phase-split sensitivity (PLAN.md §3.4): do the headline mention-layer
results hold within coarse chronological phases?

Assignment rule (transparent, data-derived, deliberately coarse):
- EARLY: catalogue names Amenhotep III as the pharaoh, OR the letter's
  person list contains ʿAbdi-Aširta and not Aziru.
- LATE: catalogue names Amenhotep IV/Tutankhamun/Smenkhkare, OR the
  letter contains Aziru and not ʿAbdi-Aširta.
- UNASSIGNED otherwise (both, neither, or conflicting signals) - reported,
  never imputed. Letters where reign and Amurru anchors conflict are
  unassigned.

This is a sensitivity analysis, not a temporal claim: the phases are
ordinal buckets around the Amurru succession, the one anchor the corpus
itself dates (ʿAbdi-Aširta's death, EA 101).

Writes phase_split_report.md.
"""

import csv
import random
from collections import Counter

from oracc_lib import DERIVED, ROOT
from phase2_analysis import fmt_dict, fmt_table
from phase3_analysis import (bipartite_null_clustering, build_mention,
                             betweenness_rows, load_letter_persons)

SEED = 4711
EARLY_PHARAOHS = ("amenhotep iii",)
LATE_PHARAOHS = ("amenhotep iv", "tutankhamun", "smenkhkare", "akhenaten")


def assign_phase(named_pharaoh, group):
    reign = ""
    np_ = (named_pharaoh or "").lower()
    if any(p in np_ for p in EARLY_PHARAOHS):
        reign = "early"
    elif any(p in np_ for p in LATE_PHARAOHS):
        reign = "late"
    amurru = ""
    has_abdi = "abdiasirta" in group or "sons-of-abdiasirta" in group
    has_aziru = "aziru" in group
    if has_abdi and not has_aziru:
        amurru = "early"
    elif has_aziru and not has_abdi:
        amurru = "late"
    if reign and amurru and reign != amurru:
        return "unassigned"  # conflicting anchors
    return reign or amurru or "unassigned"


def main():
    rng = random.Random(SEED)
    rows = load_letter_persons()
    named = {}
    with (DERIVED / "edges_corr.csv").open() as fh:
        for r in csv.DictReader(fh):
            named[r["id_text"]] = r["named_pharaoh"]

    for r in rows:
        r["phase"] = assign_phase(named.get(r["id_text"], ""), set(r["group"]))

    counts = Counter(r["phase"] for r in rows)
    L = []
    a = L.append
    a("# Phase-Split Sensitivity (early vs late Amarna)")
    a("")
    a("Generated by `scripts/phase_split.py` (seed 4711). Assignment: reign")
    a("identification where catalogued, else the Amurru-succession anchor")
    a("(ʿAbdi-Aširta-only letters = early, Aziru-only = late); conflicts and")
    a("no-signal letters stay unassigned.")
    a("")
    a(f"- letters: {dict(counts)} of {len(rows)} "
      f"({100 * counts['unassigned'] / len(rows):.0f}% unassigned - honest floor)")
    a("")
    for phase in ("early", "late"):
        sub = [r for r in rows if r["phase"] == phase]
        g = build_mention(sub)
        a(f"## {phase} ({len(sub)} letters)")
        a("")
        cc = g.transitivity_undirected(mode="zero")
        a(fmt_dict({"persons": g.vcount(), "dyads": g.ecount(),
                    "observed CC": round(cc, 4)}))
        a(fmt_dict(bipartite_null_clustering(sub, rng)))
        a("")
        a("Top betweenness:")
        a("")
        a(fmt_table(betweenness_rows(g, top=6)))
        a("")
    a("## Reading")
    a("")
    a("The sensitivity question is whether the full-corpus conclusions are an")
    a("artifact of aggregating two political eras. Compare each phase's CC to")
    a("its own bipartite null and its broker list to the full-corpus one; if")
    a("the small-world excess and the Aziru/Yanḥamu brokerage appear within")
    a("phases (allowing that ʿAbdi-Aširta replaces Aziru in the early era by")
    a("construction), aggregation is not driving the results.")
    a("")
    (ROOT / "phase_split_report.md").write_text("\n".join(L))
    print(f"wrote phase_split_report.md; phases: {dict(counts)}")


if __name__ == "__main__":
    main()
